// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApPEwCgjyPd2_3gFCq49zhRd_7QNWCLlo',
    appId: '1:830060103596:android:32ab0b18ec9de0a4455c09',
    messagingSenderId: '830060103596',
    projectId: 'parliament1-531d3',
    databaseURL: 'https://parliament1-531d3-default-rtdb.firebaseio.com',
    storageBucket: 'parliament1-531d3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPk916_qhGxwR3a57pRBVy7uHbuWaQkPA',
    appId: '1:830060103596:ios:fcb379ad514e70b0455c09',
    messagingSenderId: '830060103596',
    projectId: 'parliament1-531d3',
    databaseURL: 'https://parliament1-531d3-default-rtdb.firebaseio.com',
    storageBucket: 'parliament1-531d3.firebasestorage.app',
    androidClientId:
        '830060103596-h0ld1ts9litpolup75m0npsoj6relm46.apps.googleusercontent.com',
    iosBundleId: 'com.example.parliamentApp',
  );
}
